spring:
  application:
    name: coflo-api
  profiles:
    active: local
    include: oauth

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_REVIEW_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    com.reviewping.coflo: debug
    web: debug
    org.springframework.security.web:
      authentication: debug
      FilterChainProxy: debug

crypto-key: ${CRYPTO_KEY}

domain-webhook-url: ${COFLO_WEBHOOK_URL}

mattermost-logger:
  base-url: ${MATTERMOST_WEBHOOK_URL}

otel:
  instrumentation:
    micrometer:
      enabled: true
