services:
  postgresql:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_API_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dev-compose-scripts:/docker-entrypoint-initdb.d
    networks:
      - my_network
  redis:
    image: redis:latest
    hostname: ${REDIS_HOST}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  postgres_data:

networks:
  my_network:
    driver: bridge
