spring:
  application:
    name: coflo-review
  main:
    keep-alive: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_REVIEW_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

logging:
  level:
    com.reviewping.coflo: debug

openai:
  api:
    key: ${OPENAI_API_KEY}
    organization: ${OPENAI_ORGANIZATION}
    project: ${OPENAI_PROJECT}

git-clone-directory: ${GIT_CLONE_DIRECTORY}

otel:
  instrumentation:
    micrometer:
      enabled: true
