#!/usr/bin/env bash

# 현재 브랜치 이름 가져오기
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
COMMIT_MSG_FILE=$1

if [[ $BRANCH_NAME =~ [a-z]+\/(S11P31A210-[0-9]+)-.* ]]; then
    JIRA_ID="${BASH_REMATCH[1]}"
else
  echo "분야/S11P31A210-숫자-이슈요약 형식의 브랜치명을 사용해주세요." >&2
  exit 0
fi

echo "현재 브랜치: $BRANCH_NAME"
echo "추출된 JIRA ID: $JIRA_ID"

if ! grep -q "Jira: $JIRA_ID" "$COMMIT_MSG_FILE"; then
        echo -e "\n\nJira: $JIRA_ID" >> "$COMMIT_MSG_FILE"
fi
